# Generated by Django 3.0.1 on 2019-12-24 23:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='work.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='work.Company')),
            ],
            options={
                'permissions': (('can_create_work', 'Can create new work'),),
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Cancelled'), (3, 'Finished')], default=0)),
                ('week_limit', models.IntegerField(default=40)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='work.Manager')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='work.Work')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='work.Worker')),
            ],
            options={
                'ordering': ['status'],
                'permissions': (('can_hire', 'Can hire workers'),),
                'unique_together': {('work', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Cancelled')], default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Worker')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktimes', to='work.WorkPlace')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('total_worked_time', models.FloatField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='work.Worker')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='work.WorkPlace')),
            ],
        ),
    ]
